### ISSUE TITLE
Canvas invisible on second render

### ISSUE THREAD

**Issue by RSpace** [ngokevin/aframe-react#10]
Apologies for submitting a very custom issue that likely is not the fault of aframe-react, but I could really use a second pair of eyes on this. I've built a small example of switching between a normal html/css rendering and an aframe rendering of the same data using aframe-react starting from the boilerplate.

The example is running here: http://immersionftw.com/meetup-vr/
The code is here: https://github.com/RSpace/aframe-meetup-example

If you:
1) Switch to "VR mode" by clicking the button
2) Switch back to "2d mode" by looking down and clicking the red sphere with the cursor
3) Switch to "VR mode" once again by clicking the button

... you will see that the canvas is not shown the second time "VR mode" is entered. By profiling the canvas in Firefox it is clear that the canvas is indeed rendered the second time, so it might be something as simple as a styling issue. But I just can't figure out why it's different the second, and if the problem is on my code, aframe-react or aframe-core.

Any ideas?

**Comment by RSpace** [comment]
Btw, I'm using this slightly modified version of aframe-core to make React able to add and remove the canvas as part of the `a-scene` element: https://github.com/aframevr/aframe-core/pull/762

**Comment by ngokevin** [comment]
Sorry, didn't see this.

Can you post a snippet of how you are entering/exiting VR mode?

**Comment by RSpace** [comment]
Yes, it's essentially just an if-sentence looking at the prop it is given:

```
class Wrapper extends Component {
  render() {
    const { vrMode } = this.props

    if (vrMode) {
      return (
        <div>
          <Scene>
            <Camera><Cursor/></Camera>
            <Members/>
            <VRModeSwitcher/>
          </Scene>
        </div>
      )
    } else {
      return (
        <div>
          <VRModeSwitcher/>
          <Members/>
        </div>
      )
    }

  }
}
```

I'll try to reproduce in a simple example.

**Comment by ngokevin** [comment]
Ah, I see. I think in the next version of A-Frame, this will work better as we will render the canvas within the scene. Currently, it's appended to the body, so you'll have that leftover canvas.

**Comment by RSpace** [comment]
I actually made that change to A-Frame to make the switch work just once. I have the problem using the dev branch of aframe-core including that change. I'll try to reproduce and isolate in a minimal setup asap.

**Comment by ngokevin** [comment]
Ah, that's right. Yeah, an example would help to see what's happening.
