### ISSUE TITLE
Laser controls not working

### ISSUE THREAD

**Issue by JP-Dorman** [ngokevin/aframe-react#105]
So I've got the basic vive controllers to work, but the laser controls don't seem to want to work.

I'm using this snippet: `<a-entity laser-controls="hand: right" raycaster="objects: .links; far: 5;" line="color: #118A7E"></a-entity>`

Which I've pasted into both an aframe-react project and a vanilla A-Frame project. The snippet works in vanilla but the controller model doesn't even show up in aframe-react. 

Also <a-entity vive-controls="hand: left"></a-entity> works for a basic controller, but when a button is depressed it doesn't return to its default colour and stays blue?

**Comment by ngokevin** [comment]
Is your A-Frame version up to date?

**Comment by JP-Dorman** [comment]
Damn. So it is. But I guess this is why npm update didn't work earlier, it says v0.5.0 is wanted:

Package        Current  Wanted  Latest  Location
aframe          0.5.0       0.5.0      0.6.1    aframe-react-boilerplate
gh-pages      0.12.0     0.12.0    1.0.0    aframe-react-boilerplate
react-scripts  0.9.5       0.9.5      1.0.13  aframe-react-boilerplate

**Comment by JP-Dorman** [comment]
That fixed it, sorry for the newbie question!

**Comment by ngokevin** [comment]
np
