### ISSUE TITLE
Pass array or object as position instead of "0 1 -5"?

### ISSUE THREAD

**Issue by meta-meta** [ngokevin/aframe-react#12]
I'm wondering if you have any strong opinions on how this should work. It's inconvenient to have to convert a Vector3 into a string that a-frame can work with. Should this be handled by aframe-react? Or should this be some external utility function? Likewise for rotation and scale, maybe even color: convert RGB to Hex?

I currently do this:
```es2015
let {x,y,z} = someVectorObject
position={`${x} ${y} ${z}`}
```

would be nice to be able to do this:
```es2015
position={someVectorObject}
```

and/or

```es2015
position={[x, y, z]}
```

**Comment by ngokevin** [comment]
Yeah, that would be nice. I wonder of passing an {x, y, z} object works already. For taking an array, I think I can make that happen on the A-Frame level.

**Comment by meta-meta** [comment]
Passing an {x, y, z} object does not work. I believe aframe parses the "x y z" string into an {x y z}

I don't know that it would be advantageous to accept an array at the aframe level. I believe you'd have to JSON.stringify([x, y, z]) to pass the array as an attribute. If a developer has to do that, they might as well just transform it to a string that aframe already accepts.

And then in the pure HTML case, I definitely would prefer "x y z" to '["x","y","z"]'.

**Comment by mayognaise** [comment]
:+1:

**Comment by ngokevin** [comment]
https://github.com/ngokevin/aframe-react/pull/20
