### ISSUE TITLE
how to use raycaster in aframe-react?

### ISSUE THREAD

**Issue by SaudTauqeer** [ngokevin/aframe-react#136]
How do I use raycaster on my cursor to work only on entities with certain id?
```
 <Entity
        raycaster="objects: [data-raycastable]" --> this doesn't work obviously.
        // color={cursorColor}
        primitive="a-cursor"
        animation__click={{
          property: "scale",
          startEvents: "click",
          from: "0.1 0.1 0.1",
          to: "1 1 1",
          dur: 150
     />
```

**Comment by lorgan3** [comment]
Hi @SaudTauqeer it might be that you're just missing a `#` in your selector to select an id.
It seems this is the recommended way to configure your components with this wrapper: `raycaster={{ objects: ["#data-raycastable"] }}`

**Comment by SaudTauqeer** [comment]
Thank you that did the trick.
