### ISSUE TITLE
Can you use aframe-text-component with this

### ISSUE THREAD

**Issue by alexwasner** [ngokevin/aframe-react#15]
You wrote a cool text component, but I cant seem to get it to be wrapped since its not a primitive. Any suggestions on to how this would work?

**Comment by ngokevin** [comment]
I don't recommend using primitives with aframe-react, you can use the basic Entity building block. React already has component/wrapping logic.

`<Entity text={{ text: 'hello' }}>`

or maybe wrap it if you want like `<Text/>`

```
export default props => <Entity text={...props.text} material={...props.material}>
```

**Comment by ngokevin** [comment]
Because the whole premise of `aframe-react` is to expose the `<Entity/>` building block :)

Else you'd just use raw React

**Comment by ngokevin** [comment]
btw hoping to move that component into the aframe repo some time :)

**Comment by alexwasner** [comment]
So just for clarification, you are saying I should build my own <Text/> component instead of attempting to use your aframe-text-component? I'm just trying to render some text onto the canvas.

**Comment by ngokevin** [comment]
You can use the component. I recommend not using primitives like `<a-cube>` or `<a-sphere>` since React kind of solves creating components.

You can use the text component. Do `<Entity text={{ ...textProps }}>`

**Comment by ngokevin** [comment]
Kind of confusing because of the overloading name of components :/

**Comment by alexwasner** [comment]
Hmm getting `Unknown component attribute: text`. Maybe its just a require issue. Thanks for the clarification on primatives.

**Comment by ngokevin** [comment]
Np, happy to debug any code you have here.

**Comment by alexwasner** [comment]
Ah, your demo has 
```var AFrame = require('aframe-core');
var textComponent = require('aframe-text-component');
AFrame.registerComponent('text', textComponent);```
 instead of 
```
var textComponent = require('aframe-text-component').component;```
