### ISSUE TITLE
Invoke .emit() on a ref for Animation?

### ISSUE THREAD

**Issue by maxkrieger** [ngokevin/aframe-react#16]
As from [the docs](https://aframe.io/docs/core/animation.html#Begin), following this pattern:
```
<Entity ref="box" geometry="primitive: box" material="opacity: 1">
  <Animation attribute="material.opacity" begin="fade" to="2 2 2" />
</Entity>
```
```
this.refs.box.emit("fade");
```
```
Uncaught TypeError: _this.refs.box.emit is not a function
```

How does one properly implement this?

**Comment by ngokevin** [comment]
Hmm...isn't `ref` a callback nowadays? https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by maxkrieger** [comment]
Although the string method is outdated, it can still give you access to the domelement pretty easily.

**Comment by ngokevin** [comment]
Ah. So what does `refs.box` give you? Is that an `<a-entity>` DOM element?

**Comment by maxkrieger** [comment]
Oop, it gives an `Entity` :confused:. Is there a better way to implement this if any?
![screen shot 2016-02-16 at 15 10 39](https://cloud.githubusercontent.com/assets/2660634/13089605/78a29164-d4bf-11e5-9773-5ed1d22fb58a.png)

**Comment by ngokevin** [comment]
Use the callback?

**Comment by ngokevin** [comment]
I guess react-dom.findDOMNode

**Comment by ngokevin** [comment]
Somehow React should let you grab the DOM element, else write a component.
