### ISSUE TITLE
Is it possible to render Sky Entity with image ?

### ISSUE THREAD

**Issue by whatifif** [ngokevin/aframe-react#17]
I know Sky entity can be rendered like below:
  <Entity geometry={{primitive: 'sphere', radius: 5000}}     material={{color: props.color || '#73CFF0', shader: 'flat', src: '#sky'}}    scale="1 1 -1"/>

But when I tried to render image instead of color, the image is not rendered.
  <Entity geometry={{primitive: 'sphere', radius: 5000}}     material={{ src: "./skyimage.png" }}    scale="1 1 -1"/>

I wonder if it is possible to render Sky Entity with image using aframe-react.

**Comment by maxkrieger** [comment]
Try changing your image src string to `url(myimage.png)`. I think that sort of thing should be noted somewhere in the docs as it drove me a little nuts too :stuck_out_tongue:

**Comment by whatifif** [comment]
Yes, you are right.

The image url should be `url(${img-url})`   if img-url is variable.
` ` is template quote.
