### ISSUE TITLE
Is it possible to render a-model using aframe-react? 

### ISSUE THREAD

**Issue by whatifif** [ngokevin/aframe-react#18]
I see there is a-model tag in the original a-frame.
a-model uses '.dae' data format.

Is it possible to render a-model using aframe-react?

**Comment by meta-meta** [comment]
aframe-react doesn't expose the aframe primitives but those are all merely entities witha combination of components

to load a model, you can use a loader component and you'll likely want rotation, position and scale components:

```
<Entity loader={{src: 'url(models/my_model.dae)', format: 'collada'}}
              scale="1 1 1"
              rotation="0 180 0"
              position="0 0 0">
</Entity>
```

**Comment by ngokevin** [comment]
If you are requiring `aframe` in your project, `<a-model>` should be there and usable within or as a React component.
