### ISSUE TITLE
Merge component props when overridden.

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/aframe-react#2]
For example:

```
const material = {color: 'red', side: 'double'}
<Entity material={{metalness: 1, roughness: 0}} {...material}/>
```

That should combine all the material component properties together. Currently, the second instance of material will overwrite the first one.

**Comment by shea-hawkins** [comment]
What should this do on conflict? Warn user and default to second?

**Comment by ngokevin** [comment]
It should try to merge if defined twice. Not sure if that is possible.

**Comment by ngokevin** [comment]
This can be up to the React Component how to merge.
