### ISSUE TITLE
Event Cleanup

### ISSUE THREAD

**Issue by sheldonj** [ngokevin/aframe-react#34]
I might be missing something fundamental here, but can you explain to me how event handlers are cleaned up in this lib?

**Comment by ngokevin** [comment]
I manually added several events. But need to have a better way to handle them. I recommend using A-Frame's entity-component framework for the logic, and use React for state and views.

**Comment by ngokevin** [comment]
Added `events` prop, and there's a PR for registering all `on*` as event handlers
