### ISSUE TITLE
Detach Events

### ISSUE THREAD

**Issue by azmartone** [ngokevin/aframe-react#39]
We need a way to remove the events that get attached to the element.

```
            <Entity
                onMouseEnter={this.onMouseEnter}
                onMouseLeave={this.onMouseLeave}
                onClick={this.onClick}
                >
```

**Comment by azmartone** [comment]
Actually, those props are from aframe-mouse-cursor-component

**Comment by ngokevin** [comment]
That is true though, we do need to detach event props when those props are removed.

**Comment by jesstelford** [comment]
An idea on that front: Store the event map as a component property (`this._eventMap`), then only attach a single event listener (regardless of if `this._eventMap` has any values or not), then inside the event listener, the event name becomes the key into `this._eventMap`.

We'd need to also add a `componentWillReceiveProps()` to regenerate the `this._eventMap` object, then everything else is handled without having to update anything or add / remove any event listeners.

**Comment by ngokevin** [comment]
v4.0.x will now diff the `events` map and register/deregister as necessary.
