### ISSUE TITLE
core:schema:warn about component/system 'undefined' when using <a-primitives>

### ISSUE THREAD

**Issue by Zacqary** [ngokevin/aframe-react#40]
I get that the gist of `aframe-react` is that we're not supposed to be using stuff like `<a-sphere>` in lieu of always using the `<Entity>` component. But being able to call `<a-sphere>` A) saves a lot of typing, and B) seems to work.

I figured the problem would be that React has patchy support for custom attributes, but as it turns out:
```javascript
<Scene embedded>
   <a-sphere position="0 0 -15" color="red" radius="1"/>
</Scene>
```
renders perfectly fine. The only problem I get are these warning in the console:
```
core:schema:warn Unknown property `color` for component/system `undefined`. +2ms
core:schema:warn Unknown property `radius` for component/system `undefined`. +3ms
```

I don't think I've run into any other issues besides that, so far. But what are these warnings about? They don't show up when I build my spheres with `<Entity>`

**Comment by ngokevin** [comment]
It's not against using `<a-sphere>`, it's just that `aframe-react` doesn't have to do anything special in that case, and React Components can sort of replicate the creation of such pre-fabbed entities.

The warnings are probably just a bug with the A-Frame primitives. It's near the top on my list of stuff to polish, but my list is pretty long...

**Comment by ngokevin** [comment]
might have been fixed

**Comment by natesena** [comment]
Still getting the issue when I create my own component
