### ISSUE TITLE
Reports of boolean serialization not working on scene with physics

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/aframe-react#44]
- `<Scene  id="sceneobj" stats physics="debug: true" >`
- `<Scene  id="sceneobj" stats physics={{debug: 'true'}} >`

**Comment by ngokevin** [comment]
Will work now with v4.0.x

**Comment by jlieb10** [comment]
@ngokevin were you doing this using aframe-physics-system?

**Comment by ngokevin** [comment]
I think so? Also maybe with just like `debug` component alone.

**Comment by PButcher** [comment]
This bug seems to be present again with v4.3.0 and React 16.0 using `aframe-physics-system`.

My workaround is to use `<a-scene physics="debug: true">...</a-scene>` again.

Is anyone else able to confirm?
