### ISSUE TITLE
Assert management

### ISSUE THREAD

**Issue by jonasfj** [ngokevin/aframe-react#48]
I think we need to create elements for: `a-asserts`, `a-assert-item`, `audio`, `img`, `video`
https://aframe.io/docs/0.4.0/core/asset-management-system.html

Those can't be created with `Entity`.

**Comment by jonasfj** [comment]
Thoughts? I suspect it something we can quickly write..

**Comment by ngokevin** [comment]
Thanks for feedback. They don't need to be wrapped with React do they? They are usable as DOM elements

**Comment by jonasfj** [comment]
Sure, but if the `<Scene>` tag is made with react... We need a react wrapper right?
```jsx
import {Scene, Entity} from 'aframe-react';

let f = props => {
  return (
    <Scene>
      <a-assets></a-assets>
    </Scene>
  );
}
```
isn't valid JSX as `a-assets` isn't defined. Also probably can't be, as it's not a valid JS identifier.

**Comment by ngokevin** [comment]
custom elements work fine with react now, it'll just do a createElement.
 
we don't need a react wrapper, even if the Scene is a React Component. The Scene is a React Component because it does serialization to A-Frame for A-Frame components

**Comment by samburgers** [comment]
Is this the correct way to go about adding an image to the Sky component via `a-assets` ?

```
render () {
    return (
        <Scene>
            <a-assets>
                <img id="my-image" src="assets/images/my-image.png" />
            </a-assets>
            <Sky src="#my-image"></Sky>
        </Scene>
    )
}
```

**Comment by aayushis12** [comment]
You will have to import a-assets first from aframe-react. Otherwise react will consider a-asssets as a native html tag or look for something with the same name considering it a custom react tag.
