### ISSUE TITLE
Let's provide the primitives

### ISSUE THREAD

**Issue by jonasfj** [ngokevin/aframe-react#49]
As I understand primitives: https://aframe.io/docs/0.4.0/primitives/

They are just `a-entity` tags with a nice combination of components and default values, as well a easy access attributes.

We could probably implement them all very quickly, any reason not to provide them?

**Comment by ngokevin** [comment]
What would be the reason to provide them? They are usable as is from aframe-react, there's even a primitive prop.

**Comment by jonasfj** [comment]
I couldn't do `<Entity id="pine" primitive="a-collada-model" src="#pine2" position="0 0 -15" />`
For some reason the `src` property isn't passed down... I think had similar issues with other primitives.

Maybe I'm missing something, or maybe we're missing that specific property somewhere...
I'll admit anything 3d is far outside my comfort zone - I'm just having some holiday fun :)

**Comment by ngokevin** [comment]
There was a PR today to fix primitives, there was a typo, I released that version

You could also just use `<a-collada-model>`.

Hope it's fun :)

**Comment by jonasfj** [comment]
Oh, I didn't know that worked in react... nevermind :)
