### ISSUE TITLE
Interop with DOM components

### ISSUE THREAD

**Issue by clayallsopp** [ngokevin/aframe-react#5]
Hey @ngokevin, what do you think of some API like:

```
render () {
  return <Scene>
    <Entity>
      <div>
        Hello World
      </div>
    </Entity>
  </Scene>;
}
```

I'd be rather excited to do this if you can point me in the right direction. I'm not totally sure of the perf impact (the current method of blending WebGL and HTML seems to be a CSS trick), but might be fun

it looks like React is already adding the correct DOM to the tree, just need to make the aframe entity aware of the children.

<img width="288" alt="screen shot 2015-12-22 at 3 20 13 pm" src="https://cloud.githubusercontent.com/assets/153704/11965004/9ce92eb0-a8bf-11e5-88b9-e1166f548138.png">

I have some intuition on how to do this:

1. Create a new aframe component based on [the boilerplate](https://github.com/ngokevin/aframe-component-boilerplate)
2. The aframe component is basially an aframe plane
3. we create a `THREE.CSS3DObject` in `update()`, bound to the plane's position and rotation, using the first child DOM element (which is what React creates for us)

that sound right? any gotchas I'm missing?

Main source of inspiration is [this comment](https://www.reddit.com/r/WebVR/comments/3x58mr/aframe_by_mozvr_building_blocks_for_the_virtual/cy4nhit) and [the linked post](http://learningthreejs.com/blog/2013/04/30/closing-the-gap-between-html-and-webgl/

**Comment by ngokevin** [comment]
To embed an HTML page within an A-Frame scene, yeah we'd use a component. Either an iframe component or a 2D renderer. However, we would not mix regular HTML markup within the scene as that breaks the model.

To give ideas, a possible API might be:

```html
<a-assets>
  <div id="page">MY STUFF</div>
</a-assets>
<a-scene>
  <a-entity pageplane="src: #page"></a-entity>
  <!-- Or. -->
   <a-entity pageplane="<div>MY STUFF</div>"></a-entity>
```

The API can be decided at the will of the implementer. Either way, it'd be outside the scope of the aframe-react layer

**Comment by clayallsopp** [comment]
Thanks for the follow-up, got something working: https://vid.me/Zw2B

One gotcha is that this technique (http://jeanlescure.io/blog/threejs-and-css-3d-transforms/) requires two scenes and two renderers. I hacked some logic into a-scene and VREffect to account for this, not sure if that's something that should be merged into a-frame core?

**Comment by ngokevin** [comment]
You could maybe do this with a custom A-Frame component that accepts selectors to DOM elements and renders them. 

```html
<a-assets>
  <div id="mydiv">Hello, World</div>
</a-assets>
<a-scene>
  <a-entity dom="#mydiv"></a-entity>
</a-scene>
```

```js
AFRAME.registerComponent('dom', {
  schema: {
    default: '' 
  },
  
  update: {
    this.el.object3D.add(// Add your CSS3DObject here. );
  }
});
```

**Comment by ngokevin** [comment]
Check out https://github.com/scenevr/htmltexture-component

But not aframe-react related
