### ISSUE TITLE
Do not discard non-component properties when using primitives

### ISSUE THREAD

**Issue by jsantell** [ngokevin/aframe-react#50]
Hacking on a short hand library for using aframe react's primitives in [aframe-react-components](https://github.com/jsantell/aframe-react-components). Essentially mapping:

`<Sphere radius={5} />`
to
`<Entity primitive='a-sphere' radius={5} />`
which should map to
`<a-sphere radius='5' />`

But currently, the short hand properties provided by primitives [are discarded](https://github.com/ngokevin/aframe-react/blob/71a7698d474f52f17d6250acd1b30d37e3bfcd41/src/index.js#L106), requiring a user to define with the full component mapping, like `<Entity primitive='a-sphere' geometry={{ radius: 5 }} />`.

Is it possible to know these mappings for stock primitives? Dug around a bit, and couldn't seem to find a way to expose these via the AFRAME global. Still new to aframe-react, so I might be missing something, but if this sounds good (and it's possible to get these mappings), I'll work on a PR

**Comment by ngokevin** [comment]
Ah, that's a nasty bug.

There should be like `AFRAME.primitives['a-box'].mappings`, but maybe we can just skip that check altogether?

**Comment by jsantell** [comment]
The objects stored at `AFRAME.primitives.primitives['a-box']` seem to only be the constructor, although geometries expose their schema `AFRAME.geometries.box.schema` which could get us close to just acknowledging valid properties (since Aframe handles the mapping anyway), but this would only work for primitives based on geometry, not things like `<a-cursor>` or `<a-camera>`. I'll hack on some solutions

**Comment by ngokevin** [comment]
Might be simple to remove the check for invalid properties. A-Frame will handle raising warnings about that.

**Comment by jhsu** [comment]
instead of returning an `<Entity />` the library could just return a `React.createElement`, that way there's no prop proxying needed. Essentially treating the primitive as a normal dom element.

see: https://github.com/jsantell/aframe-react-components/pull/1

**Comment by ngokevin** [comment]
Primitives can also take components, which needs the layer of serialization that converts objects passed as props to strings that HTML can understand.

**Comment by jhsu** [comment]
that's right...

**Comment by ngokevin** [comment]
Fixed in v4.0.x. Nothing being discarded now, everything is sent thru `.setAttribute()`.
