### ISSUE TITLE
<Entity> turns into a blue 1x1x1 box when React re-renders it (unknown circumstances)

### ISSUE THREAD

**Issue by jonikorpi** [ngokevin/aframe-react#58]
When my React app re-renders some of my components, some of the `<Entities>` seem to lose their geometry, turning into 1x1x1 boxes. They also turn blue, for some reason. 

I'm unclear on the exact circumstances, but these entities always reside deep in the component hierarchy and possibly have events bound to them.

I've managed to jury rig together an example of this happening by stripping down my app as much as possible, but you'll sadly need to jump through some hoops:

1. Open https://world-vufbpyzwci.now.sh/
2. Use the sticky cursor to click on the lone white hex and wait a sec.
3. You should now see a green box surrounded by white hexes. Click one of the hexes.
4. The white hexes on the opposite side of where you clicked should turn into blue boxes.

This is an early build of a hex-based game. What's happening is that the green box is moving onto the hex you clicked, meaning React is:

- Mounting new hexes (now white) in the direction you clicked
- Unmounting some of the hexes in the opposite direction (now invisible)
- Re-rendering the rest of the hexes (now blue boxes)

If you open the A-Frame inspector, you can see all mounted hexes with IDs like `clickable-thing-x-y`. And here's the source of the React component containing the hex `<Entity>`: https://github.com/jonikorpi/world/blob/blue-box-debugging/components/Action.js#L162

I've had this issue for months but haven't filed an issue since I can't pinpoint what makes it occur. Let me know if I can do anything else to help figure this out.

P.S. This issue could be related? https://github.com/ngokevin/aframe-react/issues/57

**Comment by ngokevin** [comment]
I've added a unit test case for this. v4 of aframe-react should resolve most issues and #57 has been resolved. https://github.com/ngokevin/aframe-react/commit/b92638af6f3a76f9e73b9cf0fcd6832134f13dfd

Try it out. Although there will be migration steps (e.g., no more `onXXX` handlers and have to pass {x,y,z} objects or strings for coordinates, not arrays).
