### ISSUE TITLE
The distribute version is on the repo?

### ISSUE THREAD

**Issue by davesnx** [ngokevin/aframe-react#62]
Hey @ngokevin 

I open this because I saw a user complaining about master being not syncronized with npm.
The potentiall issue could be that master is bug-free meanwhile the registry could have some bug (related with `a-asset-items` or others...) If it's true. 

For now I only can see that there's no diff between
```bash
diff
https://raw.githubusercontent.com/ngokevin/aframe-react/master/dist/index.js
vs
https://unpkg.com/aframe-react@3.4.1
```

> `unpkg` is a cdn of the npm registry

Well... going back to the issue, I would like to have the dist out of the repo basically for have the distribute version in a CDN and atomic (be able to re-create the dist version), as well we would have cleaner PRs.

I can see the benefit of having the dist in the repo as a shareable URL, but since there's options like `unpkg`, we can provide this URLs as a direct asset.

Thanks!
PS: I didn't express very well on this issue :(

**Comment by ngokevin** [comment]
OK!

**Comment by ngokevin** [comment]
Well, the `dist/` is the package.json `main`, where it's already compiled. It's not for distribution, just where it's generated.

**Comment by ngokevin** [comment]
Will close since `dist/` is the built version (with Babel) that npm points to.
