### ISSUE TITLE
Remove props passed with null

### ISSUE THREAD

**Issue by lennerd** [ngokevin/aframe-react#64]
It would be nice, if the `Entity` component filters received props to exclude `null` values and instead uses to the default A-Frame value. IMHO this would more conform with the way React handles `null` values.

This would also make it simpler to add default props passed to entities. For example:

``` js
class Camera extends Component {
  static defaultProps = {
    position: null,
  };

  render() {
    const { position } = this.props;

    const camera = {
      userHeight: 1.6,
    };

    return (
      <Entity
        position={position}
        camera={camera}
        look-controls
      />
    );
  }
}
```

At the moment this produces the following error at https://github.com/ngokevin/aframe-react/blob/master/src/index.js#L104:
`Uncaught TypeError: Cannot read property 'constructor' of null`

With a okay from you @ngokevin I could build a small PR for this.

**Comment by jhsu** [comment]
imo it should still pass the property to the `React.createElement`, so essentially some better condition checks and then `serialProps[component] = null`. null is still a value and should still be passed down to components as a value. in this case, the final aframe element won't care about it, but I think it's still important to pass it down.

**Comment by ngokevin** [comment]
Yeah, `null` is a valid value. If you want to filter it out, you can remove it from your props.

**Comment by lennerd** [comment]
@ngokevin Still struggling with this. So how do I remove a aframe component again if I'm not able to use null or some kind of falsy value??

**Comment by lennerd** [comment]
Forget my question. Just found out that passing `undefined` will remove the component again, at least from the element. Having problems with light sources. But I think this is more related to `AFRAME` or `THREE` itself.

**Comment by ngokevin** [comment]
Can also do something like

```
var components = {};
if (someFlag) {
  components.geometry = {primitive: 'box'};
}
return <Entity {...components}/>
```

**Comment by lennerd** [comment]
@ngokevin Thanks for the example! Thats what I also end up using.
