### ISSUE TITLE
Issue with text-component not being rendered

### ISSUE THREAD

**Issue by aurbinaUCF** [ngokevin/aframe-react#66]
Hello, Im trying to put some text on my aframe-react project but the following:

`<Entity bmfont-text={{text: 'HELLO WORLD'}} position="{[0, 1, -5]}"/>`

Does nothing... I have the components imported as necessary and I dont receive any errors.. it just does not render. I have also tried this with the standard text-component as part of kframe. Same result.

**Comment by jbreckmckye** [comment]
Which version of aframe are you bundling? I had the same issue when using `aframe-v0.5.0.min.js` - see [here](https://github.com/aframevr/aframe/issues/2403).

**Comment by jhsu** [comment]
@aurbinaUCF are you using aframe 0.5?
you can use [built-in text component](https://aframe.io/docs/0.5.0/components/text.html) which uses `value`: `text={{value: 'HELLO WORLD'}}`

**Comment by aurbinaUCF** [comment]
Yes sorry, Ive been busy. I am using 0.5.0, the problem ended up being that the opacity for some reason was defaulted to 0.

**Comment by natesena** [comment]
I am having the same issue and have played with opacity. Currently using 0.7.1
