### ISSUE TITLE
Not wrapping render return value in <Entity> makes entire aframe rendering fail silently

### ISSUE THREAD

**Issue by RSpace** [ngokevin/aframe-react#7]
I'm making a few stupid, yet time consuming, mistakes with aframe-react. One of them is this code:

```
import { Component } from 'react'
import Avatar from '../components/Avatar'

class Avatars extends Component {
  render () {
    let members = this.props.members
    return (
      <div>
        {members.map(member => {
          return <Avatar key={member.id} id={member.id} name={member.name} photoUrl={member.photo_url}/>
        })}
      </div>
    )
  }
}
```

It works when I replace my stupid `<div></div>` wrapper with `<Entity></Entity>`, but with the code above, I got nothing rendered at all, and no error. It would be really nice with an exception explaining the problem and how to fix it.

**Comment by ngokevin** [comment]
In A-Frame, ```<a-entity>``` acts as the grouping element. They are the 3D comparison to ```<div>```s 

Can you file an issue to A-Frame to throw warnings for this? Thanks!
