### ISSUE TITLE
<Entity> implicitly expects React to be defined

### ISSUE THREAD

**Issue by RSpace** [ngokevin/aframe-react#8]
This code:

```
import {Entity} from 'aframe-react'
import {Component} from 'react'

class Avatars extends Component {
  render () {
    return (
      <Entity>
      </Entity>
    );
  }
}
```

results in this error: `Uncaught ReferenceError: React is not defined` in the line where it tries to render `<Entity>`. Seems like this component implicitly expects React to be imported be the parent component, as changing line 2 to `import React, {Component} from 'react'` fixes the problem.

But that shouldn't really be necessary, should it?

**Comment by ngokevin** [comment]
Yeah, that's weird. I'll check it out once I get back.

**Comment by RSpace** [comment]
This seems to be a general React issue. This code gives the same `ReferenceError`:

```
import {Component} from 'react'

export default class Member extends Component {
  render () {
    return (
      <div className="member-component">
      </div>
    );
  }
}
```

That is, until `React` is added to the import statement. So not an issue specific to aframe-react.
